version: 2.1

orbs:
 win: circleci/windows@2.2.0

jobs:
  build:
    executor: win/default     
    
    steps:
      - checkout
      - run: dotnet build
      - run: curl --data build=true -X POST $Docker_Hub_Trigger
