 version: 2.1
 
 deployment:
  dockerhub:
   branch: master
   commands:
    - $Docker_Hub_Trigger

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor: win/default     
    
     steps:
       - checkout
       - run: dotnet build
